# setup python language server
kind: pipeline
type: exec
name: default

trigger:
  branch:
  - language-server
  event:
  - push

steps:
  - name: deploy
    commands:
      - |  # https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#pipe-dockerfile-through-stdin
        docker build -t pywebio-language-server -f- . <<EOF
        FROM python:3
        WORKDIR /usr/src/app
        ADD ./server .
        RUN pip3 install --no-cache-dir -r requirements.txt
        EXPOSE 8080
        CMD pylsp --ws --host 0.0.0.0 --port 8080
        EOF
      - docker rm -f language-server || exit 0
      # make `memory-swap` same as `memory-` to disable swap
      - docker run --restart=always --name=language-server --memory="1g" --memory-swap="1g" --cpus="1" -d pywebio-language-server
