name: Build frontend

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: web
      - name: Move web branch to master
        run: |
          git fetch --unshallow origin
          git reset --hard master || exit 0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build frontend
        working-directory: ./frontend
        run: |
          yarn
          yarn prepare
          mv lib ../docs
      - name: Push
        run: |
          git config --global user.email "wang0.618@qq.com"
          git config --global user.name "${{ github.actor }}"
          git config --global credential.helper '!f() { sleep 1; echo "username=${{ github.actor }}"; echo "password=${GH_TOKEN}"; }; f'

          git add docs
          git commit -m "Build `date`" || exit 0
          git push -f -u origin || exit 0
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}