name: Restart Runner

on:
  schedule:
    - cron: '0 * * * *'    # Runs every hour

jobs:
  restart:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl restart pywebio-server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}