name: Restart Runner

on:
  schedule:
    - cron: '0 * * * *'    # Runs every hour
  workflow_dispatch:

jobs:
  restart:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          cd server
          flyctl apps restart pywebio-server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
